### ISSUE TITLE
install windows 11 updater

### ISSUE THREAD

**Issue by zacnoo** [TheSpud-xyz/thespud.xyz#11]
saving this for later:
```css
:root{
  --pane-base-color:white;
  --lighting-intensity: 0.25;
}
.material\:glass{
  background:color-mix(in srgb, var(--pane-base-color), rgba(128,128,128,0) 20%);
  box-shadow: 
  inset 1px 1px 2px rgba(255,255,255,var(--lighting-brightness)),
  inset -1px -1px 2px rgba(0,0,0,calc(var(--lighting-brightness) / 3)),
  0px 0px 0px 1px #80808060
/*  inset 0px 0px 0px 1px #60606080*/
  ;

  -webkit-backdrop-filter:blur(5px);
  transition:300ms;
}
```
